### ISSUE TITLE
Redis链接易断开

### ISSUE THREAD

**Issue by xiaozhangup** [YiC200333/XConomy#102]
**Version of XConomy**  
XConomy V2.22.1

**Server version**  
Paper 1.20.1

**Storage-type**  
MySQL

**Describe the issues**  
服务器启动几分钟后，Redis链接断开，控制台提示
[09:12:44] [XConomyRedisSub/WARN]: [XConomy] Error during creation
[09:12:44] [XConomyRedisSub/WARN]: me.yic.xc_libs.redis.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.util.RedisInputStream.readByte(RedisInputStream.java:46)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.Protocol.process(Protocol.java:126)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.Protocol.read(Protocol.java:192)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:282)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.BinaryJedisPubSub.process(BinaryJedisPubSub.java:104)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.BinaryJedisPubSub.proceed(BinaryJedisPubSub.java:96)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xc_libs.redis.jedis.Jedis.subscribe(Jedis.java:3785)
[09:12:44] [XConomyRedisSub/WARN]: 	at XConomy-Bukkit-2.22.1.jar//me.yic.xconomy.data.redis.RedisThread.run(RedisThread.java:36)

自此，跨服务器转账失效，同步概率失效
隔壁HuskSync对这个Redis的链接良好

---

**(option)XConomy's config.yml**

**(option)Screenshots**

**Comment by YiC200333** [comment]
试下2.24.4版本
