### ISSUE TITLE
Redis connection exception

### ISSUE THREAD

**Issue by EterLuu** [YiC200333/XConomy#111]
**Version of XConomy**  
XConomy V2.24.4

**Server version**  
git-Pufferfish-17 (MC: 1.20.1)

**Storage-type**  
MySQL

**Describe the issues**  
There's no issue in 2.24.1, but after updating to 2.24.3 **or** 2.24.4, the issue occurred:
```
[11:38:35] [Server thread/INFO]: [XConomy] Loading server plugin XConomy v2.24.4
[11:38:42] [Server thread/INFO]: [XConomy] Enabling XConomy v2.24.4
[11:38:42] [Server thread/INFO]: [XConomy] UUID-Mode: Default
[11:38:42] [Server thread/INFO]: [XConomy] Language: CHINESE
[11:38:42] [Server thread/INFO]: [XConomy] 数据保存方式 - MySQL
[11:38:42] [Server thread/INFO]: [me.yic.xc_libs.zaxxer.hikari.HikariDataSource] [XConomy] - Starting...
[11:38:42] [Server thread/INFO]: [me.yic.xc_libs.zaxxer.hikari.pool.HikariPool] [XConomy] - Added connection com.mysql.cj.jdbc.ConnectionImpl@7b6b2a7a
[11:38:42] [Server thread/INFO]: [me.yic.xc_libs.zaxxer.hikari.HikariDataSource] [XConomy] - Start completed.
[11:38:42] [Server thread/INFO]: [XConomy] MySQL连接正常
[11:38:42] [Server thread/INFO]: [XConomy] Redis连接异常
[11:38:42] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "me.yic.xc_libs.redis.jedis.JedisPool.getResource()" because "me.yic.xconomy.utils.RedisConnection.jedis" is null
[11:38:42] [Server thread/WARN]: 	at XConomy-Bukkit-2.24.4.jar//me.yic.xconomy.utils.RedisConnection.getResource(RedisConnection.java:107)
[11:38:42] [Server thread/WARN]: 	at XConomy-Bukkit-2.24.4.jar//me.yic.xconomy.utils.RedisConnection.connectredis(RedisConnection.java:85)
[11:38:42] [Server thread/WARN]: 	at XConomy-Bukkit-2.24.4.jar//me.yic.xconomy.data.DataLink.create(DataLink.java:82)
[11:38:42] [Server thread/WARN]: 	at XConomy-Bukkit-2.24.4.jar//me.yic.xconomy.XConomy.onEnable(XConomy.java:103)
[11:38:42] [Server thread/INFO]: [XConomy] XConomy已成功卸载
[11:38:50] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: XConomy
[11:39:08] [Server thread/INFO]: [AuctionHouse] Registered Service Provider XConomy for Vault's Economy API
[11:39:11] [Server thread/INFO]: [QuickShop-Hikari] Using economy system: XConomy
[11:39:15] [Server thread/INFO]: [Lands] [Integrations] Successfully integrated Vault economy into economy system. Name: XConomy Banks: true
	at me.yic.xconomy.data.DataFormat.isMAX(DataFormat.java:99) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.depend.economy.Vault.depositPlayer(Vault.java:158) ~[XConomy-Bukkit-2.24.4.jar:?]
[12:04:55] [Craft Scheduler Thread - 130 - XConomy/WARN]: [XConomy] Plugin XConomy v2.24.4 generated an exception while executing task 694954
java.lang.NullPointerException: Cannot invoke "me.yic.xc_libs.redis.jedis.JedisPool.getResource()" because "me.yic.xconomy.utils.RedisConnection.jedis" is null
	at me.yic.xconomy.utils.RedisConnection.getResource(RedisConnection.java:107) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.data.redis.RedisPublisher.publishmessage(RedisPublisher.java:29) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.data.DataCon.SendMessTask(DataCon.java:211) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.data.DataCon.lambda$changeplayerdata$0(DataCon.java:138) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.data.DataFormat.isMAX(DataFormat.java:99) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.depend.economy.Vault.depositPlayer(Vault.java:158) ~[XConomy-Bukkit-2.24.4.jar:?]
[12:16:17] [Server thread/INFO]: [XConomy] Disabling XConomy v2.24.4
[12:16:17] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling XConomy v2.24.4 (Is it up to date?)
	at me.yic.xc_libs.redis.jedis.BinaryJedisPubSub.unsubscribe(BinaryJedisPubSub.java:37) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.data.redis.RedisSubscriber.close(RedisSubscriber.java:43) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.utils.RedisConnection.close(RedisConnection.java:51) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.XConomyLoad.Unload(XConomyLoad.java:72) ~[XConomy-Bukkit-2.24.4.jar:?]
	at me.yic.xconomy.XConomy.onDisable(XConomy.java:182) ~[XConomy-Bukkit-2.24.4.jar:?]

```
I use latest version of bitnami redis.

**Comment by YiC200333** [comment]
多谢反馈

**Comment by YiC200333** [comment]
临时解决方案：给你的Redis服务器加个密码
