### ISSUE TITLE
Error occurred while enabling XConomy

### ISSUE THREAD

**Issue by TKwSni** [YiC200333/XConomy#112]
**Version of XConomy**  
XConomy V2.24.4

**Server version**  
git-Purpur-2049 1.20.1

**Storage-type**  
SQLite (default I normally use mysql, but I tried clean install)

**Describe the issues**  
```
[10:43:54] [Server thread/ERROR]: Error occurred while enabling XConomy v2.24.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "org.bukkit.Bukkit.getPluginCommand(String)" is null
  at me.yic.xconomy.XConomy.onEnable(XConomy.java:131) ~[XConomy-Paper-2.24.4.jar:?]
  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
  at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2049]
  at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

---

**(option)XConomy's config.yml**
default
**(option)Screenshots**

**Comment by YiC200333** [comment]
Do you install CMI or other same plugin? set their alias command (ex: bal command) to false

**Comment by TKwSni** [comment]
got it, thanks! that was it
