### ISSUE TITLE
[Error] Invalid number argument in "pay" command results in an unhandled exception

### ISSUE THREAD

**Issue by adamtomi** [YiC200333/XConomy#12]
This is the command (obviously the syntax is wrong):
`ProGamerMeli issued server command: /pay 8000 ProgamerAnna`

And it results in this exception, but I guess it should be handled:
```
[21:17:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pay' in plugin XConomy v2.7.18
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-191]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-191]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[?:git-Paper-191]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[?:git-Paper-191]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-191]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NumberFormatException
at java.math.BigDecimal.<init>(BigDecimal.java:497) ~[?:1.8.0_262]
at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_262]
at java.math.BigDecimal.<init>(BigDecimal.java:809) ~[?:1.8.0_262]
at me.yic.xconomy.data.DataFormat.formatString(DataFormat.java:17) ~[?:?]
at me.yic.xconomy.Commands.onCommand(Commands.java:102) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-191]
... 18 more
```

**Comment by YiC200333** [comment]
Thanks for your feedback
I will fix this error in the next version

**Comment by YiC200333** [comment]
2.7.22 version is fixed

**Comment by adamtomi** [comment]
You're awesome!
