### ISSUE TITLE
Error with towny

### ISSUE THREAD

**Issue by AffectAge** [YiC200333/XConomy#14]
[20:48:23 WARN]: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT] Abort due to constraint violation (UNIQUE constraint failed: xconomynon.account)
[20:48:23 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1010)
[20:48:23 WARN]: at org.sqlite.core.DB.newSQLException(DB.java:1022)
[20:48:23 WARN]: at org.sqlite.core.DB.execute(DB.java:861)
[20:48:23 WARN]: at org.sqlite.core.DB.executeUpdate(DB.java:902)
[20:48:23 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:98)
[20:48:23 WARN]: at me.yic.xconomy.data.SQL.createNonPlayerAccount(SQL.java:120)
[20:48:23 WARN]: at me.yic.xconomy.data.SQL.selectNonPlayer(SQL.java:219)
[20:48:23 WARN]: at me.yic.xconomy.data.DataCon.getBalNonPlayer(DataCon.java:59)
[20:48:23 WARN]: at me.yic.xconomy.data.caches.NonPlayerCache.getBalanceFromCacheOrDB(NonPlayerCache.java:20)
[20:48:23 WARN]: at me.yic.xconomy.Vault.getBalance(Vault.java:124)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.object.economy.adapter.VaultEconomyAdapter.getBalance(VaultEconomyAdapter.java:33)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.TownyEconomyHandler.getBalance(TownyEconomyHandler.java:196)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.object.economy.BankAccount.getHoldingBalance(BankAccount.java:179)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.object.economy.Account.setBalance(Account.java:158)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.command.TownCommand.newTown(TownCommand.java:2535)
[20:48:23 WARN]: at com.palmergames.bukkit.towny.command.TownCommand.lambda$newTown$8(TownCommand.java:2476)
[20:48:23 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[20:48:23 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[20:48:23 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[20:48:23 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[20:48:23 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[20:48:23 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[20:48:23 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[20:48:23 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by YiC200333** [comment]
What is your XConomy version？

**Comment by AffectAge** [comment]
2.17.8

**Comment by YiC200333** [comment]
try the last version(2.17.24)
I fixed a serious non player data save problem in 2.17.18 version
