### ISSUE TITLE
Account not existing + console error

### ISSUE THREAD

**Issue by JorisvD01** [YiC200333/XConomy#143]
**Version of XConomy**  
XConomy V2.26.3

**Server version**  
Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

**Storage-type**  
MySQL

**Describe the issues:**
When trying to check the balance of some players, or give money to some the plugin responds; "account not existing" and gives this error in the console, even tho the user that the money was sent to, or the balance was checked from is a user on the server and has money in their account.

**(option)XConomy's config.yml**
https://pastebin.com/X5SCLrB9

**Console error:**
`[14:42:07 WARN]: [XConomy] Future Timeout
[14:42:07 WARN]: java.util.concurrent.TimeoutException
[14:42:07 WARN]: at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
[14:42:07 WARN]: at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.utils.CompletableFutureManager.supplyAsync(CompletableFutureManager.java:34)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.data.DataLink.getPlayerData(DataLink.java:157)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.data.DataCon.getPlayerDatai(DataCon.java:76)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.data.DataCon.getPlayerData(DataCon.java:48)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.command.core.CommandBalance.onCommand(CommandBalance.java:98)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.command.core.CommandCore.onCommand(CommandCore.java:118)
[14:42:07 WARN]: at XConomy-Paper-2.26.3.jar//me.yic.xconomy.Commands.onCommand(Commands.java:33)
[14:42:07 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:42:07 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:42:07 WARN]: at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987)
[14:42:07 WARN]: at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[14:42:07 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[14:42:07 WARN]: at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:324)
[14:42:07 WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:308)
[14:42:07 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2354)
[14:42:07 WARN]: at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2314)
[14:42:07 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[14:42:07 WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[14:42:07 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:42:07 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:42:07 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1338)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:42:07 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1315)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1308)
[14:42:07 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1286)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[14:42:07 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:42:07 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)`

**Comment by GGTRYGH** [comment]
I have the same issue any enhancement?
