### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by ghost** [YiC200333/XConomy#16]
Hello, I have this Mysql error on my server spigot 1.9.4.
However all my connection information is correct especially since my other plugins work with mysql.

12:05:42] [Server thread/INFO]: [XConomy] Enabling XConomy v2.8.3
[12:05:42] [Server thread/INFO]: [XConomy] Found PlaceholderAPI
[12:05:42] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: xconomy
[12:05:42] [Server thread/INFO]: [XConomy] PlaceholderAPI successfully hooked
[12:05:42] [Server thread/INFO]: [XConomy] M?thode de sauvegarde - MySQL
[12:05:42] [Server thread/INFO]: [XConomy] Impossible de se connecter ? la base de donn?es -----
[12:05:42] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:05:42] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:862)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2331)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2084)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[12:05:42] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[12:05:42] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
[12:05:42] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[12:05:42] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[12:05:42] [Server thread/WARN]: 	at me.yic.xconomy.data.DatabaseConnection.setGlobalConnection(DatabaseConnection.java:64)
[12:05:42] [Server thread/WARN]: 	at me.yic.xconomy.data.SQL.con(SQL.java:26)
[12:05:42] [Server thread/WARN]: 	at me.yic.xconomy.data.DataCon.create(DataCon.java:24)
[12:05:42] [Server thread/WARN]: 	at me.yic.xconomy.XConomy.onEnable(XConomy.java:86)
[12:05:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[12:05:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[12:05:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:05:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[12:05:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[12:05:42] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[12:05:42] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[12:05:42] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[12:05:42] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getServerCharset(ConnectionImpl.java:3004)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendConnectionAttributes(MysqlIO.java:1908)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1837)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1207)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2254)
[12:05:42] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2285)
[12:05:42] [Server thread/WARN]: 	... 24 more
[12:05:42] [Server thread/INFO]: [XConomy] Connexion infructueuse ? MySQL
[12:05:42] [Server thread/ERROR]: Error occurred while enabling XConomy v2.8.3 (Is it up to date?)
java.lang.NullPointerException
	at me.yic.xconomy.XConomy.onDisable(XConomy.java:132) ~[?:?]
	at me.yic.xconomy.XConomy.onEnable(XConomy.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by YiC200333** [comment]
What is your version of MySQL?

**Comment by ghost** [comment]
Version MySQL: 8.0.21

**Comment by YiC200333** [comment]
Xconomy is not compatible with MySQL, I will fix this in the next version

**Comment by YiC200333** [comment]
XConomy is not compatible with MySQL8 in spigot 1.8 - 1.11

**Comment by ghost** [comment]
Why is it not compatible? Which version is he using?

**Comment by YiC200333** [comment]
I fixed this problem, please download the XConomy 2.8.4 version and DatabaseDrivers

DatabaseDrivers: https://github.com/YiC200333/DatabaseDrivers/releases

**Comment by ghost** [comment]
What is the database drivers for?

**Comment by YiC200333** [comment]
mysql-connector 8.0.21

**Comment by ghost** [comment]
[14:22:48] [Server thread/INFO]: [XConomy] Enabling XConomy v2.8.4
[14:22:48] [Server thread/INFO]: [XConomy] Found PlaceholderAPI
[14:22:48] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: xconomy
[14:22:48] [Server thread/INFO]: [XConomy] PlaceholderAPI successfully hooked
[14:22:48] [Server thread/INFO]: [XConomy] Found DatabaseDrivers
[14:22:48] [Server thread/INFO]: [XConomy] M?thode de sauvegarde - MySQL
[14:22:48] [Server thread/INFO]: [XConomy] Impossible de se connecter ? la base de donn?es -----
[14:22:48] [Server thread/WARN]: java.sql.SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:76)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
[14:22:48] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[14:22:48] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[14:22:48] [Server thread/WARN]: 	at me.yic.xconomy.utils.DatabaseConnection.setGlobalConnection(DatabaseConnection.java:84)
[14:22:48] [Server thread/WARN]: 	at me.yic.xconomy.data.SQL.con(SQL.java:27)
[14:22:48] [Server thread/WARN]: 	at me.yic.xconomy.data.DataCon.create(DataCon.java:24)
[14:22:48] [Server thread/WARN]: 	at me.yic.xconomy.XConomy.onEnable(XConomy.java:94)
[14:22:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[14:22:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:22:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:22:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[14:22:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[14:22:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[14:22:48] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[14:22:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[14:22:48] [Server thread/WARN]: Caused by: me.yic.libs.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
[14:22:48] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:22:48] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:22:48] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:22:48] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.util.TimeUtil.getCanonicalTimezone(TimeUtil.java:132)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2120)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2143)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
[14:22:48] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
[14:22:48] [Server thread/WARN]: 	... 17 more
[14:22:48] [Server thread/INFO]: [XConomy] Connexion infructueuse ? MySQL
[14:22:48] [Server thread/ERROR]: Error occurred while enabling XConomy v2.8.4 (Is it up to date?)
java.lang.NullPointerException
	at me.yic.xconomy.XConomy.onDisable(XConomy.java:140) ~[?:?]
	at me.yic.xconomy.XConomy.onEnable(XConomy.java:95) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by ghost** [comment]
It did not work

**Comment by YiC200333** [comment]
I'll fix it right away

**Comment by YiC200333** [comment]
Please download 2.8.5 version and set MySQL.timezone to CEST in the config.yml
https://github.com/YiC200333/XConomy/releases/tag/2.8.5

**Comment by ghost** [comment]
I put timezone: CEST and for test   timezone: 'CEST' but I have this error:

[15:18:59] [Server thread/INFO]: [XConomy] Enabling XConomy v2.8.5
[15:18:59] [Server thread/INFO]: [XConomy] Found PlaceholderAPI
[15:18:59] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: xconomy
[15:18:59] [Server thread/INFO]: [XConomy] PlaceholderAPI successfully hooked
[15:18:59] [Server thread/INFO]: [XConomy] Found DatabaseDrivers
[15:18:59] [Server thread/INFO]: [XConomy] M?thode de sauvegarde - MySQL
[15:19:00] [Server thread/INFO]: [XConomy] Impossible de se connecter ? la base de donn?es -----
[15:19:00] [Server thread/WARN]: java.sql.SQLException: No timezone mapping entry for 'CEST'
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:85)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
[15:19:00] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[15:19:00] [Server thread/WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[15:19:00] [Server thread/WARN]: 	at me.yic.xconomy.utils.DatabaseConnection.setGlobalConnection(DatabaseConnection.java:90)
[15:19:00] [Server thread/WARN]: 	at me.yic.xconomy.data.SQL.con(SQL.java:27)
[15:19:00] [Server thread/WARN]: 	at me.yic.xconomy.data.DataCon.create(DataCon.java:24)
[15:19:00] [Server thread/WARN]: 	at me.yic.xconomy.XConomy.onEnable(XConomy.java:94)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[15:19:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[15:19:00] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[15:19:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:19:00] [Server thread/WARN]: Caused by: me.yic.libs.mysql.cj.exceptions.WrongArgumentException: No timezone mapping entry for 'CEST'
[15:19:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[15:19:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[15:19:00] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:19:00] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.protocol.a.NativeProtocol.configureTimezone(NativeProtocol.java:2134)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.protocol.a.NativeProtocol.initServerSession(NativeProtocol.java:2143)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1310)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:967)
[15:19:00] [Server thread/WARN]: 	at me.yic.libs.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
[15:19:00] [Server thread/WARN]: 	... 17 more
[15:19:00] [Server thread/INFO]: [XConomy] Connexion infructueuse ? MySQL
[15:19:00] [Server thread/ERROR]: Error occurred while enabling XConomy v2.8.5 (Is it up to date?)
java.lang.NullPointerException
	at me.yic.xconomy.XConomy.onDisable(XConomy.java:140) ~[?:?]
	at me.yic.xconomy.XConomy.onEnable(XConomy.java:95) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by YiC200333** [comment]
try set MySQL.timezone to UTP

**Comment by YiC200333** [comment]
Sorry, I typed the wrong word

try set MySQL.timezone to UTC

**Comment by ghost** [comment]
Thanks it works!
