### ISSUE TITLE
Missing API-VERSION warning in console

### ISSUE THREAD

**Issue by simonerighi96** [YiC200333/XConomy#19]
```
[09:22:17 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[09:22:17 WARN]: java.lang.Exception
[09:22:17 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:259)
[09:22:17 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:325)
[09:22:17 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
[09:22:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
[09:22:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305)
[09:22:17 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389)
[09:22:17 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206)
[09:22:17 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
[09:22:17 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:22:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:22:19 WARN]: **Legacy plugin XConomy v2.8.11 does not specify an api-version.**
```

I'm using Paper version git-Paper-312 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

Xconomy version: v2.8.11*

**Comment by YiC200333** [comment]
Thank you for your feedback. This error will not affect the use. I will fix it in the next version

**Comment by YiC200333** [comment]
2.8.13 version is fixed
