### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by AdixePL** [YiC200333/XConomy#36]
Hello, I found a disturbing bug. When any plugin tries to take a player's coin amount, I get the error: 
```
java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
	at me.yic.xconomy.data.caches.Cache.translateUUID(Cache.java:174)
	at me.yic.xconomy.depend.economy.Vault.getBalance(Vault.java:143)
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:22)
```

**Comment by YiC200333** [comment]
Hi! Thanks for your feedback

Can you tell me your server version and XConomy plugin version?

**Comment by AdixePL** [comment]
I Am using latest version.

**Comment by YiC200333** [comment]
https://1moegrzy.oss-cn-shanghai.aliyuncs.com/XConomy-Bukkit-2.10.9.jar

I fix this problem in this version, try it and welcome feedback.
