### ISSUE TITLE
Doesnt load on 1.17.1

### ISSUE THREAD

**Issue by ehetteNandaYo** [YiC200333/XConomy#37]
Error startup on 1.17.1
```
[02:59:50] [Server thread/INFO]: [XConomy] Enabling XConomy v2.10.1
[02:59:50] [Server thread/ERROR]: Error occurred while enabling XConomy v2.10.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getString(String)" is null
	at me.yic.xconomy.utils.DataBaseINFO.getStorageType(DataBaseINFO.java:42) ~[?:?]
	at me.yic.xconomy.XConomy.allowHikariConnectionPooling(XConomy.java:214) ~[?:?]
	at me.yic.xconomy.XConomy.onEnable(XConomy.java:87) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1288]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[02:59:50] [Server thread/INFO]: [XConomy] Disabling XConomy v2.10.1
[02:59:50] [Server thread/ERROR]: Error occurred while disabling XConomy v2.10.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.scheduler.BukkitTask.cancel()" because "this.refresherTask" is null
	at me.yic.xconomy.XConomy.onDisable(XConomy.java:182) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.1.jar:git-Purpur-1288]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1288]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1288]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by ehetteNandaYo** [comment]
nvm I think it was a problem with my configs
