### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by roughanddai** [YiC200333/XConomy#42]
[19:22:56] [Server thread/INFO]: [XConomy] Enabling XConomy v2.10.1
[19:22:56] [Server thread/ERROR]: Error occurred while enabling XConomy v2.10.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.RegisteredServiceProvider.getProvider()" because "rsp" is null
	at me.yic.xconomy.depend.economy.VaultHook.load(VaultHook.java:38) ~[?:?]
	at me.yic.xconomy.depend.LoadEconomy.load(LoadEconomy.java:34) ~[?:?]
	at me.yic.xconomy.XConomy.onEnable(XConomy.java:73) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:505) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:419) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:234) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:995) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.17.1.jar:3207-Spigot-18c71bf-8537925]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by YiC200333** [comment]
谢谢反馈，会在下一个版本中修复

**Comment by YiC200333** [comment]
2.10.8版本已经修复
