### ISSUE TITLE
Could not load plugin.

### ISSUE THREAD

**Issue by Ghostttie** [YiC200333/XConomy#51]
If someone could help me solve this issue that would be awesome!

```
[30Oct2021 01:25:26.167] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/xconomy.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:381) ~[forge:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:244) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:826) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:286) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more
```

**Comment by YiC200333** [comment]
Try downloading the plugin again
