### ISSUE TITLE
player account not recognized after changing name. critical

### ISSUE THREAD

**Issue by aaa8881** [YiC200333/XConomy#53]
pretty serious issue here.

**I am not very sure if it happened because of name change.** 

1. Player with username "f79afd44-de8e-44cc-a463-a55f01ad5559" has changed name from "RustySnow152121" from "SnowCuteDragon". 

2. MySQL Table ( Select * from xconomy WHERE UID=f79afd44-de8e-44cc-a463-a55f01ad5559 ) result

UID = f79afd44-de8e-44cc-a463-a55f01ad5559
player = RustySnow152121
balance = something
hidden = something

3. Player joins , this meesage
``
[11:43:43] [Craft Scheduler Thread - 19 - XConomy/WARN]: [XConomy] Plugin XConomy v2.13.3 generated an exception while executing task 3285
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `xconomy:acb'.
	at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1722) ~[patched_1.17.1.jar:git-Paper-402]
	at me.yic.xconomy.data.DataCon.SendMessTask(DataCon.java:212) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.data.DataCon.sendudpmessage(DataCon.java:186) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.data.DataCon.prepareudpmessage(DataCon.java:176) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.data.sql.SQLCreateNewAccount.selectUser(SQLCreateNewAccount.java:184) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.data.sql.SQLCreateNewAccount.newPlayer(SQLCreateNewAccount.java:42) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.data.DataLink.newPlayer(DataLink.java:80) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at me.yic.xconomy.listeners.ConnectionListeners.lambda$onJoin$0(ConnectionListeners.java:60) ~[XConomy-Bukkit-2.13.3H.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-402]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-402]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-402]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
	``

4. xconomy is not recognizing account, thus nothing is hooked into vault for him .

**Comment by YiC200333** [comment]
Thanks for your feedback, The new version is fixed

**Comment by aaa8881** [comment]
> Thanks for your feedback, The new version is fixed

thanks. can you release it? might take some time to update to spigot I suppose.
