### ISSUE TITLE
Asynchronous player kick

### ISSUE THREAD

**Issue by Felixx61** [YiC200333/XConomy#56]
Latest velocity
Latest paper 1.18.1
Latest Xconomy configured with sql

Player logs into server, gets this message
`[15:37:19 WARN]: [XConomy] Plugin XConomy v2.14.2 generated an exception while executing task 117979
java.lang.IllegalStateException: Asynchronous player kick!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:508) ~[paper-1.18.1.jar:git-Paper-187]
        at me.yic.xconomy.data.GetUUID.kickplayer(GetUUID.java:95) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at me.yic.xconomy.data.GetUUID.doGetUUID(GetUUID.java:73) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at me.yic.xconomy.data.GetUUID.getUUID(GetUUID.java:111) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at me.yic.xconomy.data.sql.SQLCreateNewAccount.newPlayer(SQLCreateNewAccount.java:41) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at me.yic.xconomy.data.DataLink.newPlayer(DataLink.java:80) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at me.yic.xconomy.listeners.ConnectionListeners.lambda$onJoin$0(ConnectionListeners.java:56) ~[XConomy-Bukkit-2.14.2 [Beta].jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-187]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-187]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-187]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:37:20 INFO]: (!) The player Pretty_Horrific could not be found!`

**Comment by YiC200333** [comment]
Thanks for your feedback, you can return to 2.13.5 version.
I will fix this problem
