### ISSUE TITLE
Warn

### ISSUE THREAD

**Issue by SladeGit** [YiC200333/XConomy#77]
**Version of XConomy**  
latest

**Server version**  
PaperSpigot 1.19.2 latest

**Storage-type**  
MySQL

**Describe the issues**  
on server start error/warn

[20:29:36 WARN]: [XConomy] Unable to connect to database -----
[20:29:36 WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
[20:29:36 WARN]:
[20:29:36 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[20:29:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[20:29:36 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[20:29:36 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
[20:29:36 WARN]:        at XConomy-Bukkit-2.19.5.jar//me.yic.xconomy.utils.DatabaseConnection.setGlobalConnection(DatabaseConnection.java:119)
[20:29:36 WARN]:        at XConomy-Bukkit-2.19.5.jar//me.yic.xconomy.data.sql.SQL.con(SQL.java:53)
[20:29:36 WARN]:        at XConomy-Bukkit-2.19.5.jar//me.yic.xconomy.adapter.comp.DataLink.create(DataLink.java:62)
[20:29:36 WARN]:        at XConomy-Bukkit-2.19.5.jar//me.yic.xconomy.XConomy.onEnable(XConomy.java:108)
[20:29:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:29:36 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[20:29:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[20:29:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[20:29:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[20:29:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:279)
[20:29:36 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[20:29:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[20:29:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:29:36 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
[20:29:36 WARN]:
[20:29:36 WARN]: The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[20:29:36 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[20:29:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:29:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[20:29:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[20:29:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[20:29:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[20:29:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:581)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:536)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:423)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1431)
[20:29:36 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:133)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948)
[20:29:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818)
[20:29:36 WARN]:        ... 18 more
[20:29:36 WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[20:29:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:280)
[20:29:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:306)
[20:29:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347)
[20:29:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800)
[20:29:36 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[20:29:36 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.fill(ReadAheadInputStream.java:107)
[20:29:36 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:150)
[20:29:36 WARN]:        at com.mysql.cj.protocol.ReadAheadInputStream.read(ReadAheadInputStream.java:180)
[20:29:36 WARN]:        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
[20:29:36 WARN]:        at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:64)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeaderLocal(SimplePacketReader.java:81)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45)
[20:29:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:575)
[20:29:36 WARN]:        ... 24 more

other plugins working normaly database is on

**Comment by YiC200333** [comment]
This is a database connection problem, independent of xconomy
