### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by jiuwu02** [YiC200333/XConomy#89]
XConomy V2.22.1

Purpur 1.19.3-1933

SQLite

XConomay插件与UltraEconomy插件一起加载时会触发XConomay插件报错，导致关闭插件

报错内容如下
> Error occurred while enabling XConomy v2.22.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.PluginCommand.setExecutor(org.bukkit.command.CommandExecutor)" because the return value of "org.bukkit.Bukkit.getPluginCommand(String)" is null
        at me.yic.xconomy.XConomy.onEnable(XConomy.java:134) ~[[X][经济]XConomy-Bukkit-2.22.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:47:37 INFO]: [XConomy] Disabling XConomy v2.22.1
[18:47:37 INFO]: [XConomy] XConomy已成功卸载
![image](https://user-images.githubusercontent.com/107833020/233053417-17ff5c82-46ab-4229-a618-9e5825de0266.png)

日志文件
[latest.log](https://github.com/YiC200333/XConomy/files/11272189/latest.log)

XConomy配置文件
[config.txt](https://github.com/YiC200333/XConomy/files/11272224/config.txt)

**Comment by YiC200333** [comment]
谢谢反馈

**Comment by YiC200333** [comment]
这应该和CMI一样，需要把 Alias 相关的 money bal balance pay baltop 等指令修改为 false
